name: marklogic_jena

services:

  marklogic:
    image: "progressofficial/marklogic-db:11.3.0-ubi"
    platform: linux/amd64
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/marklogic/logs:/var/opt/MarkLogic/Logs
    ports:
      - "8000-8002:8000-8002"
      - "8014:8014"
